version = 0.1

[default.deploy.parameters]
stack_name = "sys-glue-ddb-crawler"
resolve_s3 = true
s3_prefix = "sys-glue-ddb-crawler"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
