version = 0.1

[default.deploy.parameters]
stack_name = "first-lambda"
s3_prefix = "first-lambda"
region = "us-west-2"
resolve_s3 = true
confirm_changeset = true
force-upload = true
capabilities = "CAPABILITY_IAM"
